defaults:
  - hydra_setup
  - meta_setup
  - _self_

model:
  model_id: distilbert-base-cased

dataset:
  json_path: /home/myurachinskiy/YSDA/ML2/ml2-papers/data/arxivData.json
  min_tag_count: 8
  max_length: 512
  val_part: 0.1

optim:
  weight_decay: 0.0005
  optim_class: torch.optim.Adam
  kwargs:
    lr: 1e-5

scheduler:
  name: cosine
  warmup_part: 0.005

data_loader:
  train:
    batch_size: 32
    shuffle: true
    pin_memory: true
    num_workers: 0
  val:
    batch_size: 32
    shuffle: false
    pin_memory: true
    num_workers: 0

training:
  epochs_num: 20
  info_steps: 1
  gradient_accumulation_steps: 1
  checkpoints_dir: checkpoints/

eval:
  probs_sum_thresholds: [0, 0.5, 0.8, 0.9, 0.95]

log:
  calculate_every: 1

exp:
  project: train_arxiv
  name: arxiv_v1
